# Generated by Django 5.2.15 on 2026-06-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("clip_path", models.CharField(max_length=255)),
                ("confidence", models.FloatField()),
                ("duration_seconds", models.FloatField(default=0)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
