# Generated by Django 5.2.15 on 2026-06-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="thumbnail_path",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
