# Generated by Django 5.2.15 on 2026-06-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0002_event_thumbnail_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="default", max_length=100)),
                ("points", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
